#application: kc8zpq-dev01
#version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- deferred: on

handlers:
# - url: /update_schema
#   script: update_schema_handler.app  # path to webapp2 application definition.
#   login: admin
#   secure: always
- url: /new
  script: golink.app
  login: required
  secure: always
- url: .*
  script: redirector.app

libraries:
- name: webapp2
  version: "2.5.2"
